pipeline:
  identifier: Build_python_1698862245208
  name: Build-Test
  orgIdentifier: default
  projectIdentifier: Harness_Testing_New
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: acapodil/python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
  tags: {}
